
-- Anaptiras DB schema (PostgreSQL)
create extension if not exists "uuid-ossp";

create table if not exists users (
  id uuid primary key default uuid_generate_v4(),
  anon_id text unique not null,
  created_at timestamptz not null default now()
);

create type room_type as enum ('ghost','crew','custom');

create table if not exists rooms (
  id uuid primary key default uuid_generate_v4(),
  owner_anon_id text not null,
  slug text unique not null,
  type room_type not null,
  title text,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  archived_at timestamptz,
  deleted_at timestamptz
);
create index if not exists idx_rooms_owner on rooms(owner_anon_id);
create index if not exists idx_rooms_active on rooms(expires_at) where archived_at is null and deleted_at is null;

create table if not exists messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references rooms(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now(),
  ip_hash text,
  lang text
);
create index if not exists idx_messages_room on messages(room_id);

create table if not exists reactions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references rooms(id) on delete cascade,
  message_id bigint,
  kind text not null,
  created_at timestamptz not null default now(),
  ip_hash text
);
create index if not exists idx_reactions_room on reactions(room_id);

create table if not exists highlights (
  id bigint generated by default as identity primary key,
  room_id uuid not null references rooms(id) on delete cascade,
  message_id bigint,
  og_url text,
  created_at timestamptz not null default now(),
  pinned boolean not null default false
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  room_id uuid not null references rooms(id) on delete cascade,
  message_id bigint,
  reason text,
  created_at timestamptz not null default now(),
  ip_hash text
);

create table if not exists quota_events (
  id bigint generated by default as identity primary key,
  anon_id text not null,
  kind text not null, -- 'free_daily' | 'ad_reward' | 'consume'
  created_at timestamptz not null default now()
);
create index if not exists idx_quota_by_user on quota_events(anon_id, created_at);

create table if not exists ad_events (
  id bigint generated by default as identity primary key,
  anon_id text,
  event text not null, -- 'impression' | 'filled' | 'rewarded_complete' | 'error'
  placement text,
  provider text,
  country text,
  created_at timestamptz not null default now()
);
